### ISSUE TITLE
Missing parameter 'address'

### ISSUE THREAD

**Issue by DrewImm** [StatelessStudio/node-mailgun#11]
```typescript
					// Add to mailing list
					await mailer
						.listAdd(this.email, this.fname, {})
						.catch((error) => {
							console.error(
								`Could not add email to list: ${this.email}`,
								error
							);
						});
```

**Comment by DrewImm** [comment]
Could not add email to list: undefined Error: Missing parameter 'address'
5:15:41 PM web.1 |      at constructor.impl (C:\Users\Drew\Dev\teachers-network-server\node_modules\mailgun-js\lib\build.js:61:21)
5:15:41 PM web.1 |      at promisifyCall (C:\Users\Drew\Dev\teachers-network-server\node_modules\promisify-call\index.js:25:15)
5:15:41 PM web.1 |      at constructor.promisifed [as create] (C:\Users\Drew\Dev\teachers-network-server\node_modules\mailgun-js\lib\build.js:105:14)
5:15:41 PM web.1 |      at C:\Users\Drew\Dev\teachers-network-server\node_modules\node-mailgun\node-mailgun.js:214:34
5:15:41 PM web.1 |      at new Promise (<anonymous>)
5:15:41 PM web.1 |      at Mailer.NodeMailgun.listAdd (C:\Users\Drew\Dev\teachers-network-server\node_modules\node-mailgun\node-mailgun.js:199:16)
5:15:41 PM web.1 |      at Object.<anonymous> (C:\Users\Drew\Dev\teachers-network-server\dist\src\routes\user.js:237:26)
5:15:41 PM web.1 |      at step (C:\Users\Drew\Dev\teachers-network-server\dist\src\routes\user.js:32:23)
5:15:41 PM web.1 |      at Object.next (C:\Users\Drew\Dev\teachers-network-server\dist\src\routes\user.js:13:53)
5:15:41 PM web.1 |      at fulfilled (C:\Users\Drew\Dev\teachers-network-server\dist\src\routes\user.js:4:58)

**Comment by DrewImm** [comment]
Issue fixed in user-space
